name: push-images
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tor_relay_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          repository: krn-dev/tor-relay
          tag_with_sha: true
          path: tor-relay

  bibliogram_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          repository: krn-dev/bibliogram
          tag_with_sha: true
          path: bibliogram
